---
# defaults file for openssl

# You can pass a list of ssl key/csr/crt/p12's to generate:
# openssl_items:
#   - name: my_openssl_key
#     common_name: my.example.com

# You can change the paths where to store each type of object (key, csr, crt,
# p12 and pkcs12). This is not required, by default the distributions regular
# location is set in `vars/main.yml`.

# This directory stores sensitive objects. (key, p12 and pkcs12)
openssl_key_directory: "/home/whoisthere"

# This directory stores public, non-persistent objects. (csr)
openssl_csr_directory: "/home/whoisthere"

# This directory stores public, persistent objects. (crt)
openssl_crt_directory: "/home/whoisthere"

# You can change the owner and group of file created by this role.
openssl_file_owner: root
openssl_file_group: root

os_nodes: |-
        {% for item in groups['nodes'] -%}
          {{ item }}{% if not loop.last %}","{% endif %}
        {%- endfor %}

os_nodes1: |-
  {% for item in groups['nodes'] -%}
    {{ loop.index }}{% if not loop.last %}","{% endif %}
  {%- endfor %}

nodes:
  - node1
  - node2
  - w
  - w
  - w
  - w
  - w
  - w
  - w


