---
# vars file for openssl

_openssl_requirements:
  default:
    - openssl
  Alpine:
    - rust
    - cargo
    - openssl
  Debian:
    - openssl
    - python3-openssl
openssl_requirements: "{{ _openssl_requirements[ansible_os_family] | default(_openssl_requirements['default']) }}"

_openssl_pip_packages:
  default:
    - pyOpenSSL
  Debian: []
openssl_pip_packages: "{{ _openssl_pip_packages[ansible_os_family] | default(_openssl_pip_packages['default']) }}"

_openssl_key_directory:
  default: /tmp
  Alpine: /etc/ssl/private
  Debian: /etc/ssl/private
  RedHat: /etc/pki/tls/private
  Suse: /etc/ssl/private

_openssl_csr_directory:
  default: /tmp
  Alpine: /etc/ssl/misc
  Debian: /etc/ssl/misc
  RedHat: /etc/pki/tls/misc
  Suse: /etc/ssl

_openssl_crt_directory:
  default: /tmp
  Alpine: /etc/ssl/certs
  Debian: /etc/ssl/certs
  RedHat: /etc/pki/tls/certs
  Suse: /etc/ssl/certs


openssl:
  root:
    private_key: "{{ openssl_key_directory }}/root-ca-key.pem"
    cert: "{{ openssl_key_directory }}/root-ca.pem"
  admin:
    private_key_temp: "{{ openssl_key_directory }}/admin-key-temp.pem"
    private_key: "{{ openssl_key_directory }}/admin-key.pem"
    csr: "{{ openssl_key_directory }}/admin.csr"
    cert: "{{ openssl_key_directory }}/admin.pem"

openssl_loop:
  - name: client
    ca:
      private_key_temp: "{{ openssl_key_directory }}/client-key-temp.pem"
      private_key: "{{ openssl_key_directory }}/client-key.pem"
      csr: "{{ openssl_key_directory }}/client.csr"
      cert: "{{ openssl_key_directory }}/client.pem"

