---
# vars file for openssl
openssl:
  root:
    private_key: "{{ openssl_key_directory }}/root-ca-key.pem"
    cert: "{{ openssl_key_directory }}/root-ca.pem"
  admin:
    private_key_temp: "{{ openssl_key_directory }}/admin-key-temp.pem"
    private_key: "{{ openssl_key_directory }}/admin-key.pem"
    csr: "{{ openssl_key_directory }}/admin.csr"
    cert: "{{ openssl_key_directory }}/admin.pem"

openssl_loop:
  - client:
      private_key_temp: "{{ openssl_key_directory }}/client-key-temp.pem"
      private_key: "{{ openssl_key_directory }}/client-key.pem"
      csr: "{{ openssl_key_directory }}/client.csr"
      cert: "{{ openssl_key_directory }}/client.pem"
  - node_1:
      private_key_temp: "{{ openssl_key_directory }}/node1-key-temp.pem"
      private_key: "{{ openssl_key_directory }}/node1-key.pem"
      csr: "{{ openssl_key_directory }}/node1.csr"
      cert: "{{ openssl_key_directory }}/node1.pem"
  - node_2:
      private_key_temp: "{{ openssl_key_directory }}/node2-key-temp.pem"
      private_key: "{{ openssl_key_directory }}/node2-key.pem"
      csr: "{{ openssl_key_directory }}/node2.csr"
      cert: "{{ openssl_key_directory }}/node2.pem"
