- name: Generate root CA private key
  openssl_privatekey:
    path: "{{ openssl.admin.private_key_temp }}"
    size: 2048
    type: RSA

- name: Convert private key to PKCS8 format with passphrase
  community.crypto.openssl_privatekey_convert:
    src_path: "{{ openssl.admin.private_key_temp }}"
    dest_path: "{{ openssl.admin.private_key }}"
    format: pkcs8

- name: create | Create ssl csr
  community.crypto.openssl_csr:
    path: "{{ openssl.admin.csr }}"
    privatekey_path: "{{ openssl.admin.private_key }}"
    mode: "777"

- name: Generate root CA certificate
  community.crypto.x509_certificate:
    path: "{{ openssl.admin.cert }}"
    privatekey_path: "{{ openssl.admin.private_key }}"
#    selfsigned_not_after: 730d
    provider: selfsigned

