- name: Generate RSA private key
  community.crypto.openssl_privatekey:
    path: "{{ openssl_csr_directory }}/root-ca-key.pem"
    type: rsa
    size: 2048

- name: Generate self-signed certificate
  openssl_certificate:
    path: "{{ openssl_csr_directory }}/root-ca.pem"
    privatekey_path: "{{ openssl_csr_directory }}/root-ca-key.pem"
    common_name: root.dns.a-record
    country: RU
    state: RU
    locality: MOSCOW
    organization: google
    organizational_unit: UNIT
    days_valid: 730