- name: Generate root CA private key
  openssl_privatekey:
    path: "{{ openssl_key_directory }}/root-ca-key.pem"
    size: 2048
    type: RSA

- name: create | Create ssl csr
  community.crypto.openssl_csr:
    path: "{{ openssl_csr_directory }}/root-ca-key.csr"
    privatekey_path: "{{ openssl_key_directory }}/root-ca-key.pem"
    common_name: root.dns.a-record
    mode: "640"

- name: Generate root CA certificate
  community.crypto.x509_certificate:
    path: "{{ openssl_csr_directory }}/root-ca.pem"
    privatekey_path: "{{ openssl_key_directory }}/root-ca-key.pem"
    selfsigned_not_after: 730d
    provider: selfsigned

