#- name: Generate RSA private key
#  community.crypto.openssl_privatekey:
#    path: "{{ openssl_csr_directory }}/root-ca-key.pem"
#    type: RSA
#    size: 2048
#
#- name: Generate self-signed certificate
#  openssl_certificate:
#    path: "{{ openssl_csr_directory }}/root-ca.pem"
#    privatekey_path: "{{ openssl_csr_directory }}/root-ca-key.pem"
#    subject: "/C=RU/ST=RU/L=MOSCOW/O=google/OU=UNIT/CN=root.dns.a-record"
#    key_usage: "keyCertSign, cRLSign"
#    days: 730
#    self_signed: yes
#

- name: Generate root CA private key
  openssl_privatekey:
    path: "{{ openssl_key_directory }}/root-ca-key.pem"
    size: 2048

- name: create | Create ssl csr
  community.crypto.openssl_csr:
    path: "{{ openssl_csr_directory }}/root-ca-key.csr"
    privatekey_path: "{{ openssl_key_directory }}/root-ca-key.pem"
    common_name: root.dns.a-record
    mode: "640"

- name: Generate root CA certificate
  openssl_certificate:
    path: "{{ openssl_csr_directory }}/root-ca.pem"
    privatekey_path: "{{ openssl_key_directory }}/root-ca-key.pem"
    csr_path: "{{ openssl_csr_directory }}/root-ca-key.csr"
    subject: "/C=RU/ST=RU/L=MOSCOW/O=google/OU=UNIT/CN=root.dns.a-record"
    key_usage: "keyCertSign, cRLSign"
    provider: selfsigned

