- name: Generate root CA private key
  openssl_privatekey:
    path: "{{ openssl.root.private_key }}"
    size: 2048
    type: RSA

- name: Generate root CA certificate
  community.crypto.x509_certificate:
    path: "{{ openssl.root.cert }}"
    privatekey_path: "{{ openssl.root.private_key }}"
#    selfsigned_not_after: 730d
    provider: selfsigned

