---

#- name: Create key directory
#  ansible.builtin.file:
#    path: "{{ openssl_key_directory }}"
#    state: directory
#    mode: "700"
#
#- name: Create csr directory
#  ansible.builtin.file:
#    path: "{{ openssl_csr_directory }}"
#    state: directory
#    mode: "755"
#
#- name: Create temp directory
#  ansible.builtin.file:
#    path: "{{ openssl_temp_directory }}"
#    state: directory
#    mode: "755"
#
#- include_tasks: create_root.yml
#
#- include_tasks: loop.yml
#  loop: "{{ nodes }}"
#  loop_control:
#    index_var: index
#
#- name: delete csr and temp dir
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: absent
#  loop:
#    - "{{ openssl_temp_directory }}"
#    - "{{ openssl_csr_directory }}"

- name: test
  debug:
    msg: "{{ os_nodes }} and {{ os_nodes1 }} and {{ os_nodes2 }}"

