---
# tasks file for openssl

#- name: Import assert.yml
#  ansible.builtin.import_tasks:
#    file: assert.yml
#  run_once: yes
#  delegate_to: localhost
#
#- name: Install requirements
#  ansible.builtin.package:
#    name: "{{ openssl_requirements }}"
#    state: present
#
#- name: Install pip packages
#  ansible.builtin.pip:
#    name: "{{ openssl_pip_packages }}"
#  when:
#    - openssl_pip_packages | length > 0

#- name: Create key directory
#  ansible.builtin.file:
#    path: "{{ openssl_key_directory }}"
#    state: directory
#    mode: "700"
#    owner: "{{ openssl_file_owner }}"
#    group: "{{ openssl_file_group }}"
#
#- name: Create csr directory
#  ansible.builtin.file:
#    path: "{{ openssl_csr_directory }}"
#    state: directory
#    mode: "755"
#    owner: "{{ openssl_file_owner }}"
#    group: "{{ openssl_file_group }}"
#
#- name: Create crt directory
#  ansible.builtin.file:
#    path: "{{ openssl_crt_directory }}"
#    state: directory
#    mode: "755"
#    owner: "{{ openssl_file_owner }}"
#    group: "{{ openssl_file_group }}"

- include_tasks: create_root.yml
#- include_tasks: loop.yml

#- name: test
#  debug:
#    msg: "{{ openssl_loop.os_nodes }}"
#  loop: "{{ openssl_loop }}"
#  loop_control:
#    loop_var: item

- include_tasks: loop.yml
  loop: "{{ nodes }}"
  loop_control:
    index_var: index


#- include_tasks: create.yml
#  loop:
#    - 1
#    - 2
#    - 3
#  loop_control:
#    loop_var: outer_item

#- name: Print index and item
#  debug:
#    msg: "Index: {{ index + 1 }} - Item: {{ item }}"
#  loop: "{{ my_list }}"
#  loop_control:
#    index_var: index